# Point Cilium to API server VIP address
k8sServiceHost: "192.168.105.100"
k8sServicePort: "6443"

# Enable kube-proxy replacement in Cilium BPF datapath
kubeProxyReplacement: "true"

# Configure Pod CIDR to match with kubeadm config networking.podSubnet
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]

# Enable L2 announcements / L2 aware LB
l2announcements:
  enabled: true

# Configure client side rate limit for the agent and operator
k8sClientRateLimit:
  qps: 50
  burst: 100

# Enable default shared Cilium Ingress Controller
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      "io.cilium/lb-ipam-ips": "192.168.105.254"

# Enable support for Gateway API in cilium
gatewayAPI:
  enabled: true

# Cilium operator configuration
operator:
  enabled: true
  replicas: 2
  rollOutPods: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            values:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: io.cilium/app
              operator: In
              values:
              - operator
          topologyKey: kubernetes.io/hostname
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

# Cilium Envoy configuration
envoy:
  enabled: true
  rollOutPods: true

# Cilium Agent configuration
rollOutCiliumPods: true

# Enable support for Gateway API in cilium
gatewayAPI:
  enabled: true

