#
# kubeadm join config for High Available (HA) Control Plane and multiple Worker nodes cluster.
#
# 'apiServerEndpoint' should have same config value than in init config for 'controlPlaneEndpoint'
# 'name' must be to unique for every node and 'node-ip' must match with 'lima0' interface
# For cluster initial bootstrap convinience 'token' is preconfigured in kubeadm init/join config files and 'unsafeSkipCAVerification' is set.
# This is INSECURE approach but as a bootstrapped cluster is assumed to be shortlived sandbox and running in closed environment this approach was considered acceptable tradeoff.
#
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.105.100:6443
    token: 9a08jv.c0izixklcxtmnze7
    unsafeSkipCAVerification: true
nodeRegistration:
  name: "worker-3"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  kubeletExtraArgs:
  - name: node-ip
    value: 192.168.105.106
  ignorePreflightErrors:
